### ISSUE TITLE
スライドづくり

### ISSUE THREAD

**Issue by tdtk** [tdtk/WWWelcome#4]

**Comment by tdtk** [comment]
とりあえず共有スライドだけ作りました．
仕様を図でまとめながら資料の足しにしていこう．
https://docs.google.com/presentation/d/1YvjunIIgP0a6AP7Nr_4NxrlJbKz81dHWz-DAY68-h08/edit?usp=sharing

**Comment by snowytom** [comment]
https://onedrive.live.com/view.aspx?resid=8BA4B784F6018897!15870&ithint=file%2cpptx&authkey=!AHhu4oxw8PYMUKE
セキュリティ的によくわからなかったから編集不可だけどとりあえず上げとく

**Comment by tdtk** [comment]
ここを意識

4. 最終審査の基準は、審査員が次の(1)から(5)の項目別に5段階で評価する。ただし、事業性は
審査項目に含めません。
(1) アイディア(課題への着眼点と課題解決への独創性を評価)
(2)実装力 (操作性、技術点、完成度)
(3) 有用度(利用者の範囲や課題の改善インパクト)
(4) ユーザーインサイト(ユーザー視点にどれだけ立って作られているか)
(5) プレゼンテーション(プレゼンの質)

**Comment by tdtk** [comment]
遅くなりました!
雑だけど研究感を減らしてもっとアプリの良さとコンセプトを押したい
https://ynuoffice365-my.sharepoint.com/:p:/g/personal/tada-taku-jp_ynu_jp/Ebe4m-E0XU9CrTAMtH22g3MBvY1bitJvwY6kDfpJ6TTUqA?e=ZJ2aW0
