### ISSUE TITLE
落とすピン種類調べ

### ISSUE THREAD

**Issue by tdtk** [tdtk/WWWelcome#6]

**Comment by tdtk** [comment]
ホットペッパー

**Comment by snowytom** [comment]
史跡系ほしいよね。

**Comment by snowytom** [comment]
https://www.chiikinogennki.soumu.go.jp/k-cloud-api/search/download/

**Comment by snowytom** [comment]
上のLink2万データあったけど、座標情報があるデータが5000件ぐらいしかなくてあんまり役に立たなさそう

**Comment by snowytom** [comment]
https://developer.yahoo.co.jp/appendix/request/rest/get.html
YahooがおおきいAPI持ってるらしいので調査中

**Comment by snowytom** [comment]
keyは取得した。600ぐらいでカテゴリ分けされてる。
使う場合はWebページの下の方にロゴを入れないといけないそうな

**Comment by tdtk** [comment]
これって位置情報で現在地付近の情報をとってくることできる？
できるならサンプルをつくってみてほしいし，
できないならGoogle map PlaceのAPI使うほうが早いかも

**Comment by snowytom** [comment]
今日中には作れると思う・
TSつかってHTTPのgetのやり方がわかればすぐだと思いますです。

**Comment by tdtk** [comment]
HTTPのgetはfetch関数をつかってみてください
https://developer.mozilla.org/ja/docs/Web/API/Fetch_API/Using_Fetch
もしCORSでひっかかってfetchが使えなかったらmasterブランチにpushしてあるhotpepperのサンプルを真似してみてください

**Comment by snowytom** [comment]
あーごめん。これ読んでなくてnode-fetch使って書いてます。
とりあえず任意の経度緯度を突っ込むと100件のお店情報は取れてる。

**Comment by tdtk** [comment]
英語というかローマ字表記みたいのとれる?

**Comment by snowytom** [comment]
取得できるのはカタカナまで。
> "ディーンアンドデルーカ・カフェ・六本木"

を

> "ディーンアンドデルーカカフェロッポンギ"

には変えれるけど、
dean&delucaにはしてくれないですねー

**Comment by tdtk** [comment]
英語対応しなくていいかな
Hotpepperとったんだけど英語はとれなくて...

**Comment by snowytom** [comment]
カテゴリ(フードとかショッピング)を英語対応して、モノの名前はヘボン表記かなんかで行くないですかね？

**Comment by tdtk** [comment]
ローマ字もとれないの...

**Comment by snowytom** [comment]
https://github.com/kazuhikoarase/jaconv
こういうのでえいや！じゃダメっすかね

**Comment by tdtk** [comment]
それでいきますか

**Comment by snowytom** [comment]
落とすピンって何が必要ですかね。
ちょっと考えてみた。

食べ物系

- 日本食
- 洋食
- お酒系(居酒屋・バー)
- 軽食系(カフェ・パン屋)

店舗
- 食品・生活用品
- 百貨店・デパート
- コンビニ
- ファッション(服、時計、アクセサリー)

遊ぶところ
- スポーツ観戦
- 遊園地とか
- お風呂

駅・バス停

病院

学校

銀行

公共
- 官公庁
- 避難所

参考　https://developer.yahoo.co.jp/webapi/map/openlocalplatform/genre.html

**Comment by tdtk** [comment]
あーいい感じですね．
そこはわりと業種コードで絞れるかどうかの技術要件を優先で分類で良いと思います．
APIは分類ごとにとってきたいな．キャッシュ節約したいので．
そういう意味では，このグループを知りたいときに絶対これは一緒に調べないみたいなところがきれいに別れてると嬉しいかも?
(なので食べ物屋は以外と細かくしすぎないほうがいい？)

**Comment by snowytom** [comment]
さっき上げたグループは業種コードを分割しないので、技術的な要件は満たせるはず(queryにorの業種コードが使えるかは明日検討します)。

**Comment by snowytom** [comment]
gcはorでとれますー.
業種コードの対応表作っておきます。

**Comment by snowytom** [comment]
JSのJSON->structみたいなのってどうやればええん？
JSONの取得までは作ったんだけどさ

**Comment by tdtk** [comment]
そもそもJSONはJSのオブジェクトなので，いい感じに型を書けばそのまま入ってくるで

**Comment by snowytom** [comment]
プログラミング全くわからん

**Comment by tdtk** [comment]
というかJSONの取得できたならそれがすでにJSのオブジェクトだから変換とかなくないという
