### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by tdtk** [tdtk/WWWelcome#9]

**Comment by snowytom** [comment]
![image](https://user-images.githubusercontent.com/19616739/68680555-3418ba80-05a5-11ea-8bea-842b2b4221c9.png)
どうすか。
ロゴ作成初めてなので、率直なご意見オネシャス～

**Comment by tdtk** [comment]
お〜めっちゃ良い！
ありがとう!!!!

そうだね〜
若干文字と絵の間にもう少しだけマージン欲しい気がするかな．
あとはやっぱりアスペクト比1:1がほしい笑

**Comment by tdtk** [comment]
たしかに色は気になるところだね
https://www.colordic.org/w
翡翠色ひすいいろ
#38b48b
とかどう?

**Comment by snowytom** [comment]
意外に受けが良くてよかったです。
コンセプトはこんな感じにするね

フォントと絵のバランスは考えときます。
安直に斜めにしてアス比改善してみた。あんまり好きじゃない。

ヒスイ色はベースカラー(背景色)の話？
班名がMatchaだし、抹茶色に近い方がいいかなーと思ってとりあえず今の色を採用してます。
ヒスイで試してみるけど、パッと見、bが強すぎる感じがしました。
bを抑えたヒスイは結構よさそう


![image](https://user-images.githubusercontent.com/19616739/68683542-4cd79f00-05aa-11ea-974b-67cac2b11c8d.png)
背景色はヒスイ。白抜きを薄ピンクにした。

**Comment by tdtk** [comment]
絵のバランスはシンプルに並べている方が好きかなー
アクセントカラーって黒のところか．確かに気になる．
逆に背景色と同系統にして，あんまり目立たないほうがオシャレ?
もしくは灰色とか

**Comment by snowytom** [comment]
![image](https://user-images.githubusercontent.com/19616739/68685520-9aa1d680-05ad-11ea-8874-ae9e00148488.png)

上二つのどっちかがよくない？
赤が唐紅、緑が緑碧を採用してます。
赤と緑で方向性が違う良さがある。赤は野心的な感じがあって、緑は調和してる感じ。

**Comment by tdtk** [comment]
二番目が好き!
